import type { Metadata } from "next";
import { Geist_Mono, Onest } from "next/font/google";
import "./styles/globals.css";
import { Header } from "./components/Header";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${onest.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <div className="flex flex-col flex-1 items-center justify-center font-sans">
          <main className="flex flex-1 w-full max-w-3xl flex-col items-center py-20 px-4 md:px-16">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
